# Generated by Django 4.0.4 on 2022-04-16 02:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('address', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='foundation_year',
            field=models.CharField(max_length=100, verbose_name='foundation_year'),
        ),
        migrations.AlterField(
            model_name='address',
            name='kladr_id',
            field=models.CharField(max_length=30, verbose_name='kladr_id'),
        ),
        migrations.AlterField(
            model_name='address',
            name='okato',
            field=models.CharField(max_length=100, verbose_name='okato'),
        ),
        migrations.AlterField(
            model_name='address',
            name='oktmo',
            field=models.CharField(max_length=100, verbose_name='oktmo'),
        ),
        migrations.AlterField(
            model_name='address',
            name='population',
            field=models.CharField(max_length=30, verbose_name='population'),
        ),
        migrations.AlterField(
            model_name='address',
            name='postal_code',
            field=models.CharField(max_length=30, verbose_name='postal_code'),
        ),
        migrations.AlterField(
            model_name='address',
            name='tax_office',
            field=models.CharField(max_length=100, verbose_name='tax_office'),
        ),
    ]
